FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY LamondLu.EmailX.Domain ./LamondLu.EmailX.Domain/
COPY LamondLu.EmailX.Infrastructure.DataPersistent ./LamondLu.EmailX.Infrastructure.DataPersistent/
COPY LamondLu.EmailX.Infrastructure.EmailService.Mailkit ./LamondLu.EmailX.Infrastructure.EmailService.Mailkit/
COPY LamondLu.EmailX.Server ./LamondLu.EmailX.Server/

WORKDIR /app/LamondLu.EmailX.Server
RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app/LamondLu.EmailX.Server
COPY --from=build /app/LamondLu.EmailX.Server/out .
ENV ASPNETCORE_URLS http://+:5000
ENTRYPOINT ["dotnet", "LamondLu.EmailService.Server.dll"]