version: "3"
services:
  emailservice:
    image: "lamondlu/emailclientserver"
    container_name: emailclientserver
    ports:
      - "5000:5000"
    hostname: emailclientserver
    links:
      - db
    depends_on: 
      - db
    build:
      context: ./LamondLu.EmailX.Server
      dockerfile: dockerfile
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    hostname: emailclientdb
    container_name: emailclientdb
    environment: 
      MYSQL_ROOT_PASSWORD: a@12345
      MYSQL_ROOT_HOST: "%"
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
