FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY LamondLu.EmailClient.Domain ./LamondLu.EmailClient.Domain/
COPY LamondLu.EmailClient.Infrastructure.DataPersistent ./LamondLu.EmailClient.Infrastructure.DataPersistent/
COPY LamondLu.EmailClient.Infrastructure.EmailService.Mailkit ./LamondLu.EmailClient.Infrastructure.EmailService.Mailkit/
COPY LamondLu.EmailClient.Server ./LamondLu.EmailClient.Server/

WORKDIR /app/LamondLu.EmailClient.Server
RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app/LamondLu.EmailClient.Server
COPY --from=build /app/LamondLu.EmailClient.Server/out .
ENV ASPNETCORE_URLS http://+:5000
ENTRYPOINT ["dotnet", "LamondLu.EmailService.Server.dll"]