version: "3.8"
services:
  emailclient:
    image: "lamondlu/emailx.client"
    container_name: emailx.client
    volumes:
      - ../config/config.local.json:/app/appsettings.json
    links:
      - db
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./LamondLu.EmailX.Client/dockerfile
  emailservice:
    image: "lamondlu/emailx.server"
    container_name: emailx.server
    ports:
      - "5080:5000"
    hostname: emailclientserver
    links:
      - db
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./LamondLu.EmailX.Server/dockerfile

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    hostname: emailclientdb
    container_name: emailclientdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: a@12345
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
